// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqOYz0ndyTXCL47h9oPWiHZZM5ZPOsVE4',
    appId: '1:821032942819:web:f59b553623604311dc99d6',
    messagingSenderId: '821032942819',
    projectId: 'eclectika-23',
    authDomain: 'eclectika-23.firebaseapp.com',
    storageBucket: 'eclectika-23.appspot.com',
    measurementId: 'G-G9MRRPKL7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT-jBNocPVTe5xhEc0kjTIgoIqkLHRxvU',
    appId: '1:821032942819:android:dc91943e6bcbaf23dc99d6',
    messagingSenderId: '821032942819',
    projectId: 'eclectika-23',
    storageBucket: 'eclectika-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWNn2Vzs7LPciB5zrEI0Z-xfItOy3AMq8',
    appId: '1:821032942819:ios:745b601cfc1b79a0dc99d6',
    messagingSenderId: '821032942819',
    projectId: 'eclectika-23',
    storageBucket: 'eclectika-23.appspot.com',
    iosClientId: '821032942819-k1ep02asngf2mtvifmfh6scb4ukc66do.apps.googleusercontent.com',
    iosBundleId: 'com.example.eclectika23OfficialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWNn2Vzs7LPciB5zrEI0Z-xfItOy3AMq8',
    appId: '1:821032942819:ios:745b601cfc1b79a0dc99d6',
    messagingSenderId: '821032942819',
    projectId: 'eclectika-23',
    storageBucket: 'eclectika-23.appspot.com',
    iosClientId: '821032942819-k1ep02asngf2mtvifmfh6scb4ukc66do.apps.googleusercontent.com',
    iosBundleId: 'com.example.eclectika23OfficialApp',
  );
}
